export type CefrBand = "A1" | "A2" | "B1";

export type CurriculumFields = {
  path_order: number;
  path_code: string;
  stage_index: number;
  stage_title: string;
  cefr_descriptor: string;
  capstone_task: string;
};

type UnitLike = {
  lesson_number: number;
  unit_code: string;
  target_band: string;
  theme_en: string;
  communicative_goal: string;
  grammar_focus: string;
  lexical_focus: string;
};

type CurriculumMeta = {
  lesson: number;
  band: CefrBand;
  pathCode: string;
  stageIndex: number;
  stageTitle: string;
  title: string;
  goal: string;
  grammar: string;
  lexical: string;
  descriptor: string;
  capstoneTask: string;
};

const STAGE = {
  sound: "Sound, Greetings, Identity",
  firstSentences: "First Sentences",
  grammarSpine: "Verb Spine and Possession",
  homeFood: "Home, Food, and Community",
  descriptions: "Descriptions, Work, and Time",
  narration: "Past Narration and Movement",
  publicLife: "Public Life and Daily Needs",
  b1Control: "B1 Narratives and Control",
} as const;

export const CURRICULUM_PATH: CurriculumMeta[] = [
  {
    lesson: 1,
    band: "A1",
    pathCode: "A1-01",
    stageIndex: 1,
    stageTitle: STAGE.sound,
    title: "Sounds and Spelling",
    goal: "Read IDIEZ spelling, pronounce core sounds, and recognize vowel length and saltillo.",
    grammar: "EHN alphabet, long vowels, consonant clusters, stress.",
    lexical: "Letters, sound words, and first pronunciation anchors.",
    descriptor: "Can recognize the sound system and read short familiar words aloud.",
    capstoneTask: "Read five new Nahuatl words aloud and identify long vowels.",
  },
  {
    lesson: 11,
    band: "A1",
    pathCode: "A1-02",
    stageIndex: 1,
    stageTitle: STAGE.sound,
    title: "Greetings and Farewells",
    goal: "Open and close a respectful everyday exchange.",
    grammar: "Greeting routines, polite formulae, and short social turns.",
    lexical: "Greetings, thanks, farewells, and courtesy expressions.",
    descriptor: "Can greet someone, say thanks, and take leave using memorized phrases.",
    capstoneTask: "Perform a two-turn greeting and farewell.",
  },
  {
    lesson: 3,
    band: "A1",
    pathCode: "A1-03",
    stageIndex: 1,
    stageTitle: STAGE.sound,
    title: "Names and Introductions",
    goal: "Introduce yourself, ask another person's name, and say where you are from.",
    grammar: "Personal pronouns, possessive name phrases, and basic subject marking.",
    lexical: "Names, identity, origin, school, and teaching words.",
    descriptor: "Can introduce self and ask simple identity questions.",
    capstoneTask: "Say your name, where you are from, and what you study.",
  },
  {
    lesson: 2,
    band: "A1",
    pathCode: "A1-04",
    stageIndex: 1,
    stageTitle: STAGE.sound,
    title: "Question Words",
    goal: "Ask and answer short information questions.",
    grammar: "Interrogatives, yes/no answers, negation, and short responses.",
    lexical: "What, where, when, why, yes, no, not yet.",
    descriptor: "Can ask basic wh-questions in familiar contexts.",
    capstoneTask: "Ask three questions about a person's day.",
  },
  {
    lesson: 34,
    band: "A1",
    pathCode: "A1-05",
    stageIndex: 2,
    stageTitle: STAGE.firstSentences,
    title: "Numbers and Counting",
    goal: "Count, give quantities, and use prices or totals in simple exchanges.",
    grammar: "Cardinal numbers and quantity phrases.",
    lexical: "Numbers, counting expressions, and common totals.",
    descriptor: "Can use numbers in very simple practical tasks.",
    capstoneTask: "Count market items and answer how many.",
  },
  {
    lesson: 4,
    band: "A1",
    pathCode: "A1-06",
    stageIndex: 2,
    stageTitle: STAGE.firstSentences,
    title: "Colors and Basic Descriptions",
    goal: "Describe objects with color, size, and quantity.",
    grammar: "Noun descriptions, adjective-like stative forms, and simple quantification.",
    lexical: "Colors, sizes, numbers, and everyday objects.",
    descriptor: "Can describe familiar objects with one or two simple properties.",
    capstoneTask: "Describe three visible objects by color and quantity.",
  },
  {
    lesson: 33,
    band: "A1",
    pathCode: "A1-07",
    stageIndex: 2,
    stageTitle: STAGE.firstSentences,
    title: "Months and Calendar Dates",
    goal: "Name months and answer when an event happens.",
    grammar: "Temporal phrases with ipan and calendar vocabulary.",
    lexical: "Months, dates, seasons, and time anchors.",
    descriptor: "Can give a familiar month or simple date.",
    capstoneTask: "Say when you will go somewhere or do something.",
  },
  {
    lesson: 6,
    band: "A1",
    pathCode: "A1-08",
    stageIndex: 2,
    stageTitle: STAGE.firstSentences,
    title: "Present-Tense Action Words",
    goal: "Talk about going, arriving, sleeping, walking, and existing.",
    grammar: "Intransitive verbs, subject prefixes, and present-time statements.",
    lexical: "Common intransitive verbs and movement words.",
    descriptor: "Can make short present-tense statements about familiar actions.",
    capstoneTask: "Say where you are going and when you will return.",
  },
  {
    lesson: 12,
    band: "A1",
    pathCode: "A1-09",
    stageIndex: 3,
    stageTitle: STAGE.grammarSpine,
    title: "Future Plans",
    goal: "Say what you will do tomorrow or later.",
    grammar: "Future suffixes, indefinite-object verbs, and wanting to do something.",
    lexical: "Speak, write, teach, learn, say, and have.",
    descriptor: "Can express a near-future intention with familiar verbs.",
    capstoneTask: "Say three things you will do tomorrow.",
  },
  {
    lesson: 13,
    band: "A1",
    pathCode: "A1-10",
    stageIndex: 3,
    stageTitle: STAGE.grammarSpine,
    title: "Doing Something to It",
    goal: "Use verbs with a specific object in food and action contexts.",
    grammar: "Object prefixes, transitive verbs, and argument structure.",
    lexical: "Eat, drink, make tortillas, give, send, and sign.",
    descriptor: "Can produce simple subject-object-verb meanings with common verbs.",
    capstoneTask: "Say what you eat, drink, and make.",
  },
  {
    lesson: 8,
    band: "A1",
    pathCode: "A1-11",
    stageIndex: 3,
    stageTitle: STAGE.grammarSpine,
    title: "Possession: Mine, Yours, Ours",
    goal: "Identify what belongs to you, someone else, or a group.",
    grammar: "Possessive prefixes and possessed noun phrases.",
    lexical: "Here, there, own/belonging, all, and possession words.",
    descriptor: "Can say that common things are mine, yours, or theirs.",
    capstoneTask: "Point out three things and say whose they are.",
  },
  {
    lesson: 9,
    band: "A1",
    pathCode: "A1-12",
    stageIndex: 3,
    stageTitle: STAGE.grammarSpine,
    title: "Family and Kinship",
    goal: "Describe family members and basic kin relationships.",
    grammar: "Possessed kinship nouns and family descriptions.",
    lexical: "Parents, siblings, grandparents, children, elders, and relatives.",
    descriptor: "Can name immediate family members and simple relationships.",
    capstoneTask: "Describe your family or an imagined family.",
  },
  {
    lesson: 20,
    band: "A1",
    pathCode: "A1-13",
    stageIndex: 4,
    stageTitle: STAGE.homeFood,
    title: "Respect and Affection: -tzin and -pil",
    goal: "Use respectful and affectionate forms for people and small things.",
    grammar: "Diminutive and honorific morphology.",
    lexical: "People, friends, elders, women, men, and social address.",
    descriptor: "Can recognize respectful and affectionate forms in familiar words.",
    capstoneTask: "Rewrite five words with respectful or affectionate nuance.",
  },
  {
    lesson: 22,
    band: "A1",
    pathCode: "A1-14",
    stageIndex: 4,
    stageTitle: STAGE.homeFood,
    title: "Food Staples",
    goal: "Name and talk about everyday foods of the home and milpa.",
    grammar: "Food nouns, direct objects, and simple preference statements.",
    lexical: "Water, beans, chili, salt, dough, tamales, squash, and staples.",
    descriptor: "Can name common foods and say what is present or wanted.",
    capstoneTask: "Say what foods are in a meal.",
  },
  {
    lesson: 21,
    band: "A1",
    pathCode: "A1-15",
    stageIndex: 4,
    stageTitle: STAGE.homeFood,
    title: "The Milpa and Field",
    goal: "Talk about what is in the field and what people grow.",
    grammar: "Existential onca, possession, and field descriptions.",
    lexical: "Cornfield, animals, crops, tools, and agricultural words.",
    descriptor: "Can describe a simple outdoor scene with familiar nouns.",
    capstoneTask: "Describe what is in a field or garden.",
  },
  {
    lesson: 23,
    band: "A1",
    pathCode: "A1-16",
    stageIndex: 4,
    stageTitle: STAGE.homeFood,
    title: "Inside the House",
    goal: "Name household objects and say where things are located.",
    grammar: "Locative and relational expressions for household scenes.",
    lexical: "House, paper, medicine, bags, metate, and home objects.",
    descriptor: "Can say what is in a house using short, practical phrases.",
    capstoneTask: "Describe five things inside a room.",
  },
  {
    lesson: 5,
    band: "A2",
    pathCode: "A2-01",
    stageIndex: 5,
    stageTitle: STAGE.descriptions,
    title: "Work and Professions",
    goal: "State and ask about occupations, work, and social roles.",
    grammar: "Occupational noun predicates and tequiti expressions.",
    lexical: "Teacher, student, worker, priest, grinder, and roles.",
    descriptor: "Can ask what someone does and answer with a simple job phrase.",
    capstoneTask: "Interview someone about their work or study.",
  },
  {
    lesson: 7,
    band: "A2",
    pathCode: "A2-02",
    stageIndex: 5,
    stageTitle: STAGE.descriptions,
    title: "Dividing the Day",
    goal: "Talk about routines across morning, afternoon, night, and seasons.",
    grammar: "Time adverbials and routine statements.",
    lexical: "Day, moon, year, early, spring, hour, and time of day.",
    descriptor: "Can describe a daily routine with simple time words.",
    capstoneTask: "Describe what you do in the morning and afternoon.",
  },
  {
    lesson: 10,
    band: "A2",
    pathCode: "A2-03",
    stageIndex: 5,
    stageTitle: STAGE.descriptions,
    title: "Appearance and Qualities",
    goal: "Describe appearance, condition, and sensory qualities.",
    grammar: "Stative predicates and adjective-like verbs.",
    lexical: "Good, dirty, dry, hot, slow, fast, alone, and appearance words.",
    descriptor: "Can describe people or things with multiple basic qualities.",
    capstoneTask: "Describe a person or object using three qualities.",
  },
  {
    lesson: 35,
    band: "A2",
    pathCode: "A2-04",
    stageIndex: 5,
    stageTitle: STAGE.descriptions,
    title: "Shapes, Sizes, and Color Detail",
    goal: "Expand descriptions with shape, size, color, and comparison words.",
    grammar: "Descriptive predicates and visual noun phrases.",
    lexical: "Round, gray, brown, pink, color, clothing, and object descriptors.",
    descriptor: "Can give fuller visual descriptions of common objects.",
    capstoneTask: "Describe an image using color, shape, and size.",
  },
  {
    lesson: 36,
    band: "A2",
    pathCode: "A2-05",
    stageIndex: 5,
    stageTitle: STAGE.descriptions,
    title: "Conditions and Evaluations",
    goal: "Evaluate whether things are difficult, expensive, cooked, pure, or damaged.",
    grammar: "Stative result forms and evaluative predicates.",
    lexical: "Hard, expensive, cooked, fallen, pure, silly, bloody, and condition words.",
    descriptor: "Can describe condition and make simple evaluations.",
    capstoneTask: "Explain whether an object, task, or meal is good, difficult, or costly.",
  },
  {
    lesson: 17,
    band: "A2",
    pathCode: "A2-06",
    stageIndex: 5,
    stageTitle: STAGE.descriptions,
    title: "Everyday Objects and Seating",
    goal: "Talk about things on tables, sitting, and household actions.",
    grammar: "Location, existential statements, and reflexive seating routines.",
    lexical: "Cup, chair, shirt, tomato, smoke, straw, and household nouns.",
    descriptor: "Can describe a simple room scene and say where someone sits.",
    capstoneTask: "Describe what is on a table and where someone sits.",
  },
  {
    lesson: 14,
    band: "A2",
    pathCode: "A2-07",
    stageIndex: 6,
    stageTitle: STAGE.narration,
    title: "Past Actions I",
    goal: "Report simple completed events such as falling, entering, fleeing, or crossing.",
    grammar: "Past-tense morphology with completed actions.",
    lexical: "Die, swim, fall, enter, flee, cross, and movement events.",
    descriptor: "Can say what happened in a short completed event.",
    capstoneTask: "Answer what happened yesterday in two sentences.",
  },
  {
    lesson: 15,
    band: "A2",
    pathCode: "A2-08",
    stageIndex: 6,
    stageTitle: STAGE.narration,
    title: "Past Actions II",
    goal: "Narrate common completed actions and reactions.",
    grammar: "Past tense with familiar verbs and short sequences.",
    lexical: "Carry, sweat, dig, cure, lie, sing, cry, and action verbs.",
    descriptor: "Can link two or three completed past actions.",
    capstoneTask: "Tell a brief story about what you did yesterday.",
  },
  {
    lesson: 24,
    band: "A2",
    pathCode: "A2-09",
    stageIndex: 6,
    stageTitle: STAGE.narration,
    title: "Going to Town I",
    goal: "Talk about going to a city, school, market, or government office.",
    grammar: "Past movement, destination phrases, and public-place nouns.",
    lexical: "Town, Mexico, school, government, market, and public places.",
    descriptor: "Can describe a past trip to a familiar place.",
    capstoneTask: "Say where you went and what you saw.",
  },
  {
    lesson: 25,
    band: "A2",
    pathCode: "A2-10",
    stageIndex: 6,
    stageTitle: STAGE.narration,
    title: "Going to Town II",
    goal: "Add sequence, distance, and still/only/also modifiers to a trip narrative.",
    grammar: "Discourse adverbs, sequencing, and distance expressions.",
    lexical: "Only, still, then, until, far, above, and also.",
    descriptor: "Can add simple connectors and modifiers to a short story.",
    capstoneTask: "Retell a trip using then, still, also, and far.",
  },
  {
    lesson: 26,
    band: "A2",
    pathCode: "A2-11",
    stageIndex: 7,
    stageTitle: STAGE.publicLife,
    title: "Buying at the Market I",
    goal: "Ask for and buy simple items at a stand.",
    grammar: "Buying verbs, prices, quantities, and polite exchange.",
    lexical: "Money, pesos, bread, oranges, shrimp, and market items.",
    descriptor: "Can make a simple purchase with quantity and price.",
    capstoneTask: "Buy two items and ask the price.",
  },
  {
    lesson: 27,
    band: "A2",
    pathCode: "A2-12",
    stageIndex: 7,
    stageTitle: STAGE.publicLife,
    title: "Market Day",
    goal: "Describe purchases and preferences in a market-day conversation.",
    grammar: "Market dialogues, wants, quantities, and polite closing.",
    lexical: "Coffee, fish, sugarcane, honey, meat, pineapple, banana, and foods.",
    descriptor: "Can participate in a short market exchange.",
    capstoneTask: "Write a four-line dialogue about buying food.",
  },
  {
    lesson: 18,
    band: "A2",
    pathCode: "A2-13",
    stageIndex: 7,
    stageTitle: STAGE.publicLife,
    title: "Likes, Dislikes, and Taste",
    goal: "Say what you like or do not like to eat and why.",
    grammar: "Preference statements, negation, and taste descriptors.",
    lexical: "Sweet potato, sour, spicy, likeness, and food preferences.",
    descriptor: "Can express simple likes and dislikes with familiar foods.",
    capstoneTask: "Say three foods you like and one you do not like.",
  },
  {
    lesson: 37,
    band: "A2",
    pathCode: "A2-14",
    stageIndex: 7,
    stageTitle: STAGE.publicLife,
    title: "Animals",
    goal: "Name animals and describe what you see in nature or near home.",
    grammar: "Noun descriptions, location, and observation statements.",
    lexical: "Animals, insects, birds, snakes, and household creatures.",
    descriptor: "Can identify familiar animals and say where they are.",
    capstoneTask: "Describe three animals you see or know.",
  },
  {
    lesson: 38,
    band: "A2",
    pathCode: "A2-15",
    stageIndex: 7,
    stageTitle: STAGE.publicLife,
    title: "More Foods and Ingredients",
    goal: "Talk about ingredients, cooking, and family food knowledge.",
    grammar: "Food-making verbs, objects, and family knowledge statements.",
    lexical: "Atole, sugar, corn, squash, alcohol, passion fruit, and ingredients.",
    descriptor: "Can describe ingredients in a simple prepared food.",
    capstoneTask: "Explain one food and what it contains.",
  },
  {
    lesson: 39,
    band: "A2",
    pathCode: "A2-16",
    stageIndex: 7,
    stageTitle: STAGE.publicLife,
    title: "Household Tools and Writing",
    goal: "Name tools, containers, letters, and objects around the home.",
    grammar: "Location, possession, and object descriptions.",
    lexical: "Letters, pots, sacks, traps, writing, and household tools.",
    descriptor: "Can describe practical household objects and where they are.",
    capstoneTask: "Say where three household objects are kept.",
  },
  {
    lesson: 40,
    band: "A2",
    pathCode: "A2-17",
    stageIndex: 7,
    stageTitle: STAGE.publicLife,
    title: "Nature and the World",
    goal: "Describe plants, water, land, trees, flowers, and natural scenes.",
    grammar: "Observation, location, and descriptive statements about nature.",
    lexical: "Seeds, lakes, leaves, roots, flowers, trees, sand, and water.",
    descriptor: "Can describe a landscape or natural scene with simple vocabulary.",
    capstoneTask: "Describe an outdoor place in four phrases.",
  },
  {
    lesson: 41,
    band: "A2",
    pathCode: "A2-18",
    stageIndex: 7,
    stageTitle: STAGE.publicLife,
    title: "People, Towns, and Community",
    goal: "Talk about people, roles, villages, towns, and community identity.",
    grammar: "People nouns, place nouns, and social-role descriptions.",
    lexical: "Town, village, person, indigenous person, roles, and community words.",
    descriptor: "Can describe people and places in a community.",
    capstoneTask: "Describe a town or village and who lives there.",
  },
  {
    lesson: 16,
    band: "B1",
    pathCode: "B1-01",
    stageIndex: 8,
    stageTitle: STAGE.b1Control,
    title: "Past Actions III",
    goal: "Narrate more complex completed events with emergence, breaking, tying, and beginning.",
    grammar: "Past-tense review with stronger verb variety and event sequencing.",
    lexical: "Break, exit, tie, begin, flash, crack, touch, and complex events.",
    descriptor: "Can narrate a short sequence of events using varied verbs.",
    capstoneTask: "Tell a six-sentence story about a problem and its outcome.",
  },
  {
    lesson: 19,
    band: "B1",
    pathCode: "B1-02",
    stageIndex: 8,
    stageTitle: STAGE.b1Control,
    title: "Commands and Requests",
    goal: "Give and respond to commands in practical situations.",
    grammar: "Imperatives, polite requests, and action prompts.",
    lexical: "Stand, write, read, turn, drive, undress, and command verbs.",
    descriptor: "Can give short instructions and understand direct requests.",
    capstoneTask: "Give a sequence of five classroom or household instructions.",
  },
  {
    lesson: 28,
    band: "B1",
    pathCode: "B1-03",
    stageIndex: 8,
    stageTitle: STAGE.b1Control,
    title: "Visiting and the Imperfect",
    goal: "Talk about visiting, passing by, and what people used to do.",
    grammar: "Imperfect aspect, house visits, and relational/location phrases.",
    lexical: "Home, door, arriving, passing by, and imperfect routines.",
    descriptor: "Can describe an ongoing or habitual past situation.",
    capstoneTask: "Describe what you used to like or do and where you were.",
  },
  {
    lesson: 29,
    band: "B1",
    pathCode: "B1-04",
    stageIndex: 8,
    stageTitle: STAGE.b1Control,
    title: "Health, Illness, and Care",
    goal: "Talk about symptoms, illness, medicine, injury, and basic care.",
    grammar: "Body/health nouns, condition statements, and needs.",
    lexical: "Bone, wound, sickness, cold, medicine, sandals, and health terms.",
    descriptor: "Can explain a simple health problem and ask for help.",
    capstoneTask: "Describe how you feel and what medicine or help you need.",
  },
  {
    lesson: 30,
    band: "B1",
    pathCode: "B1-05",
    stageIndex: 8,
    stageTitle: STAGE.b1Control,
    title: "Conditionals I",
    goal: "Make if/then statements about choices, money, and plans.",
    grammar: "Intla clauses, negation, and hypothetical outcomes.",
    lexical: "If, but, truly, never, money, animals, and conditional connectors.",
    descriptor: "Can express simple conditions and consequences.",
    capstoneTask: "Say what you will do if you have money and if you do not.",
  },
  {
    lesson: 31,
    band: "B1",
    pathCode: "B1-06",
    stageIndex: 8,
    stageTitle: STAGE.b1Control,
    title: "Ceremony and Conditional Meaning",
    goal: "Read and discuss longer cultural language around ceremony, care, and obligation.",
    grammar: "Longer conditional discourse and embedded clauses.",
    lexical: "Song, wind, sea, sky, star, ceremony, cleansing, and sacred space.",
    descriptor: "Can follow the main idea of a longer culturally situated passage.",
    capstoneTask: "Summarize a longer passage in English and identify key Nahuatl phrases.",
  },
  {
    lesson: 32,
    band: "B1",
    pathCode: "B1-07",
    stageIndex: 8,
    stageTitle: STAGE.b1Control,
    title: "Tē- and Tla- Object Markers",
    goal: "Use non-specific object markers for people and things.",
    grammar: "Tē- and tla-, generic objects, applicative-like meaning, and role suffixes.",
    lexical: "With, in/on, very, inhabitant, actor suffixes, and generic-object verbs.",
    descriptor: "Can distinguish doing something to people from doing something to things.",
    capstoneTask: "Build five verbs with tē- or tla- and explain the object type.",
  },
  {
    lesson: 42,
    band: "B1",
    pathCode: "B1-08",
    stageIndex: 8,
    stageTitle: STAGE.b1Control,
    title: "Expanded Action Vocabulary",
    goal: "Add precision to speech with verbs for belief, protection, bathing, striking, and change.",
    grammar: "Verb expansion, action chaining, and review of person marking.",
    lexical: "Loosen, hit, twist, bathe, protect, infect, urinate, believe, and actions.",
    descriptor: "Can choose more precise verbs for familiar events.",
    capstoneTask: "Retell a daily event using at least five new action verbs.",
  },
  {
    lesson: 43,
    band: "B1",
    pathCode: "B1-09",
    stageIndex: 8,
    stageTitle: STAGE.b1Control,
    title: "Adverbs and Modifiers",
    goal: "Modify actions with frequency, manner, amount, repetition, and proximity.",
    grammar: "Adverb placement, intensification, repetition, and discourse modifiers.",
    lexical: "Again, a lot, close, moreover, little by little, five times, and manner words.",
    descriptor: "Can make speech more nuanced with frequency and manner modifiers.",
    capstoneTask: "Give a B1 self-introduction using time, manner, and frequency modifiers.",
  },
];

const META_BY_LESSON = new Map(CURRICULUM_PATH.map((unit, idx) => [unit.lesson, { ...unit, order: idx + 1 }]));

export function enhanceUnit<T extends UnitLike>(unit: T): T & CurriculumFields {
  const meta = META_BY_LESSON.get(unit.lesson_number);
  if (!meta) {
    return {
      ...unit,
      path_order: unit.lesson_number,
      path_code: unit.unit_code,
      stage_index: 99,
      stage_title: "Supplemental",
      cefr_descriptor: unit.communicative_goal,
      capstone_task: unit.communicative_goal,
    };
  }

  return {
    ...unit,
    unit_code: meta.pathCode,
    target_band: meta.band,
    theme_en: meta.title,
    communicative_goal: meta.goal,
    grammar_focus: meta.grammar,
    lexical_focus: meta.lexical,
    path_order: meta.order,
    path_code: meta.pathCode,
    stage_index: meta.stageIndex,
    stage_title: meta.stageTitle,
    cefr_descriptor: meta.descriptor,
    capstone_task: meta.capstoneTask,
  };
}

export function getCurriculumAudit() {
  const byBand = CURRICULUM_PATH.reduce<Record<CefrBand, number>>(
    (acc, unit) => {
      acc[unit.band] += 1;
      return acc;
    },
    { A1: 0, A2: 0, B1: 0 },
  );

  const stages = [...new Set(CURRICULUM_PATH.map((unit) => unit.stageTitle))].length;

  return {
    totalUnits: CURRICULUM_PATH.length,
    stages,
    byBand,
  };
}
